### ISSUE TITLE
New line characters cause error in CLI only

### ISSUE THREAD

**Issue by nduckwiler** [takluyver/astsearch#12]
# Summary
Using new line characters (`\n`) will cause an error in the CLI but not in the Python API, e.g.

```bash
astsearch "if ?: ??\nelse: ??" script.py
astsearch "def ?(??): ??\nreturn ?" script.py
```

```
SyntaxError: unexpected character after line continuation character
```

This does, however, work in the Python API:

1. Define a file **script.py**
```py
if True:
  print('true!')
else:
  print('false!')

def foo(a):
  print(a)
  return a
```

2. Define a file **test.py**
```py
import astsearch

pattern = astsearch.prepare_pattern("if ?: ??\nelse: ??")
pattern_finder = astsearch.ASTPatternFinder(pattern)
matches = list(pattern_finder.scan_file("script.py"))
if len(matches) != 0:
  print('match(es) found: {} total'.format(len(matches)))
else:
  print('no matches found')
```

3. Run `python3 test.py` and see no errors
6. Repeat steps 2 and 3 but the pattern is `def ?(??): ??\nreturn ?`

I'm on a MacBook M2 with Ventura 13.5.2. Using Python 3.11.6. Tested with Terminal 2.13 and iTerm 2 Build 3.4.23.

**Comment by nduckwiler** [comment]
Here's the full error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/astsearch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/astsearch.py", line 482, in main
    ast_pattern = prepare_pattern(args.pattern)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/astsearch.py", line 455, in prepare_pattern
    pattern = ast.parse(s).body[0]
              ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    if __astsearch_wildcard: __astsearch_multiwildcard\nelse: __astsearch_multiwildcard
                                                       ^
SyntaxError: unexpected character after line continuation character

**Comment by nduckwiler** [comment]
I believe this has to do with the way that newline characters are parsed on the command line vs in a python script.

One possible solution is to replace each newline character `\\n` with an actual newline `\n`. This resolves the issue:

```py
def prepare_pattern(s):
    """Turn a string pattern into an AST pattern

    This parses the string to an AST, and generalises it a bit for sensible
    matching. ``?`` is treated as a wildcard that matches anything. Names in
    the pattern will match names or attribute access (i.e. ``foo`` will match
    ``bar.foo`` in files).
    """
    print(s) # for debugging
    s = s.replace('??', MULTIWILDCARD_NAME).replace('?', WILDCARD_NAME)
    s = s.replace('\\n', '\n') # suggested change
    print(s) # for debugging
    pattern = ast.parse(s).body[0]
```

**Comment by takluyver** [comment]
Yes, I think you're right about the cause. If we process `\n`, though, we should probably also process other backslash escapes, which is [surprisingly complicated](https://stackoverflow.com/q/4020539/434217).

In the meantime, you can workaround it by actually splitting the pattern over two lines in the shell:

```
$ astsearch "if ?: ??
> else: ??"
```

Or by using `echo -e` to convert `\n` into a newline:

```
$ astsearch "$(echo -e 'if ?: ??\nelse: ??')"
```

We could also add support for reading the pattern from stdin, to provide another way to do multi-line patterns.

**Comment by nduckwiler** [comment]
Thanks for the quick response @takluyver! I can see how it gets complicated. 

Your workarounds are sufficient for my uses, however, other users might hit the same confusion. I got the idea for using `\n` from [your blogpost here](http://takluyver.github.io/posts/astsearch-code-searching-that-knows-about-code.html), which suggests one pattern using `\n` but only provides examples using the command line.

My (very optional) suggestions are 
1. Add additional examples to the documentation using this workaround
2. Since the CLI already errs with `\n`, maybe add a helpful message with the error that warns that the CLI doesn't handle backslash escapes.

**Comment by takluyver** [comment]
Good point! I guess I must have been testing those patterns with the [Python API](https://astsearch.readthedocs.io/en/latest/api.html) rather than the command line.

Maybe we should just special-case `\n` and `\\` rather than trying to handle all backslash escapes - those are the only ones I think you're likely to need in this context. Then again, interpreting them would break patterns that use them in string literals like `astsearch '? = "\n"'`. :thinking:
